apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-client
spec:
  selector:
    matchLabels:
      app: student-app-client
  replicas: 1
  template:
    metadata:
      labels:
        app: student-app-client
    spec:
      containers:
        - name: student-app-client
          image: gauthamdharsan/springboot
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: student-app-client-service
spec:
  selector:
    app: student-app-client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
